Code to produce a heatmap using the ggplot2 function

```{r}
library(ggplot2)
library(ComplexHeatmap)
library(dplyr)
library(tidyverse)
library(circlize)

```


```{r}
getwd()
setwd("./phd/ppi/psicquicStringHippie-API")
getwd()
```

```{r}
# loading the big dataframe
df_final <- read.csv("interactors_of_VCAM1_HUMAN.csv")

# removing the first column (index from pandas) & order the columns according to alphabetic order by the interactors name
df_interactors <- subset(df_final, select = -X) %>%
    arrange(interactor_of_VCAM1_HUMAN)

```

Example of heatmap using the regular ggplot and geom_tile
```{r}
# Heatmap using the ggplot & geom_tile

# Formatting the data 
df_ggplot_string_escore <- select(df_interactors, 
                                          c("interactor_of_VCAM1_HUMAN", "string_escore")) %>% # selecting only the relevant columns # nolint
                                          replace(is.na(.), 0) %>% # replacing all the NA values with 0
                                          pivot_longer(cols="string_escore", names_to = "score") # pivoting to longer format needed for the heatmap # nolint

# Make the heatmap
ggplot(df_ggplot_string_escore,
       aes(interactor_of_VCAM1_HUMAN, score, fill = value))+
       geom_tile()

```


STRING - ESCORE
```{r}

# STRING - ESCORE

# color of the heatmap
col_string_escore = colorRamp2(c(0, 0.5), c("#f5f5f5","#da0188"))
col_string_escore(seq(0, 0.5))

# Formatting the data 
df_heatmap_string_escore <- select(df_interactors, c("interactor_of_VCAM1_HUMAN", "string_escore")) %>%
column_to_rownames(var ="interactor_of_VCAM1_HUMAN") %>%
replace(is.na(.), 0) %>%
data.matrix()

# heatmap from the string e score
H_string_escore <- Heatmap(df_heatmap_string_escore, name = "string_escore",
    row_order = order(as.numeric(gsub("row", "", rownames(df_heatmap_string_escore)))), 
    column_order = order(as.numeric(gsub("column", "", colnames(df_heatmap_string_escore)))),
    width = unit(0.25, "cm"),
    col = col_string_escore)

H_string_escore
```


STRING - CONFIDENCE SCORE
```{r}

# color of the heatmap
col_string_score = colorRamp2(c(0.4, 1), c("#f5f5f5","#558383"))
col_string_score(seq(0.4, 1))

df_heatmap_string_score <- select(df_interactors, c("interactor_of_VCAM1_HUMAN", "string_score")) %>%
column_to_rownames(var ="interactor_of_VCAM1_HUMAN") %>%
replace(is.na(.), 0) %>%
data.matrix()

# heatmap from the string e score
H_string_score <- Heatmap(df_heatmap_string_score, name = "string_score",
    row_order = order(as.numeric(gsub("row", "", rownames(df_heatmap_string_score)))), 
    column_order = order(as.numeric(gsub("column", "", colnames(df_heatmap_string_score)))),
    width = unit(0.25, "cm"),
    col = col_string_score)

H_string_score
```

INTACT SCORE
```{r}

# color of the heatmap
col_intact_score = colorRamp2(c(0, 0.66), c("#f5f5f5","#f48046"))
col_intact_score(seq(0, 0.66))

df_heatmap_intact_score <- select(df_interactors, c("interactor_of_VCAM1_HUMAN", "IntAct_score")) %>%
    mutate(IntAct_score = ifelse(str_count(IntAct_score, ",") > 0, 
                                   sapply(strsplit(IntAct_score, ","), 
                                          function(values) {
                                            values <- as.numeric(values)
                                            mean(values, na.rm = TRUE)
                                          }),
                                   IntAct_score)) %>%
    column_to_rownames(var ="interactor_of_VCAM1_HUMAN") %>%
    mutate(IntAct_score = ifelse(IntAct_score == "", 0, IntAct_score)) %>%
    mutate(IntAct_score = as.numeric(IntAct_score))

H_intact_score <- Heatmap(df_heatmap_intact_score, name = "intact_score",
    row_order = order(as.numeric(gsub("row", "", rownames(df_heatmap_intact_score)))), 
    column_order = order(as.numeric(gsub("column", "", colnames(df_heatmap_intact_score)))),
    width = unit(0.25, "cm"),
    col = col_intact_score)

H_intact_score

```

BioGRID nr of pubs
```{r}

# color of the heatmap
col_biogrid_score = colorRamp2(c(0, 4), c("#f5f5f5","#4c2c2c"))
col_biogrid_score(seq(0, 4))

df_heatmap_biogrid_pubs <- select(df_interactors, c("interactor_of_VCAM1_HUMAN", "biogrid_pubID")) %>%
    mutate(biogrid_nr_pubs = sapply(strsplit(biogrid_pubID, ","), function(x) length(unique(x)))) %>%
    column_to_rownames(var ="interactor_of_VCAM1_HUMAN") %>%
    subset(select = "biogrid_nr_pubs")

H_biogrid_nr_pubs <- Heatmap(df_heatmap_biogrid_pubs, name = "biogrid_nr_pubs",
    row_order = order(as.numeric(gsub("row", "", rownames(df_heatmap_biogrid_pubs)))), 
    column_order = order(as.numeric(gsub("column", "", colnames(df_heatmap_biogrid_pubs)))),
    width = unit(0.25, "cm"),
    col = col_biogrid_score)

H_biogrid_nr_pubs
```

APID nr of pubs
```{r}
# color of the heatmap
col_apid_score = colorRamp2(c(0, 5), c("#f5f5f5","#14b4f4"))
col_apid_score(seq(0, 5))


df_heatmap_apid_pubs <- select(df_interactors, c("interactor_of_VCAM1_HUMAN", "apid_publication")) %>%
  mutate(modified_column = gsub(",", "", apid_publication)) %>% 
  mutate(modified_column = gsub("\\)", "\\),", modified_column)) %>%
  mutate(modified_column = sub(",$", "", modified_column)) %>% 
  mutate(apid_nr_pubs = sapply(strsplit(modified_column, ", "), function(x) {
    unique_entries <- gsub("^[^(]+\\(\\s*|\\s*\\)$", "", x)  # Remove leading/trailing parentheses and spaces
    length(unique(unique_entries))
  })) %>%
  select(-modified_column) %>%
  column_to_rownames(var ="interactor_of_VCAM1_HUMAN") %>%
  subset(select = "apid_nr_pubs")

H_apid_nr_pubs <- Heatmap(df_heatmap_apid_pubs, name = "apid_nr_pubs",
    row_order = order(as.numeric(gsub("row", "", rownames(df_heatmap_apid_pubs)))), 
    column_order = order(as.numeric(gsub("column", "", colnames(df_heatmap_apid_pubs)))),
    width = unit(0.25, "cm"),
    col = col_apid_score)

H_apid_nr_pubs

```

ALL the heatmaps together
```{r}
Ht_list = H_string_escore + H_string_score + H_intact_score + H_biogrid_nr_pubs + H_apid_nr_pubs
draw(Ht_list, ht_gap = unit(0.1, "cm"))
```
